[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/gruvbox_light.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 1
decorations = "none"
startup_mode = "SimpleFullscreen"
option_as_alt = "Both"

[keyboard]
bindings = [
        { action = "ReceiveChar", key = "F", mode = "~Search", mods = "Control|Shift" },
        { action = "ReceiveChar", key = "F", mode = "~Search", mods = "Command" },
        { action = "ReceiveChar", key = "B", mode = "~Search", mods = "Control|Shift" },
        { action = "ReceiveChar", key = "B", mode = "~Search", mods = "Command" },

        # { action = "ReceiveChar", key = "P", mode = "~Search", mods = "Control|Shift" },
        # { action = "ReceiveChar", key = "P", mode = "~Search", mods = "Command" },
        # { action = "ReceiveChar", key = "N", mode = "~Search", mods = "Control|Shift" },
        # { action = "ReceiveChar", key = "N", mode = "~Search", mods = "Command" },

        # { action = "ReceiveChar", key = "P", mods = "Control|Shift" },
        # { action = "ReceiveChar", key = "P", mods = "Command" },
        # { action = "ReceiveChar", key = "N", mods = "Control|Shift" },
        # { action = "ReceiveChar", key = "N", mods = "Command" },

        # { key = "P", mods = "Control|Shift", chars = "\u001b[78;6u" },
        # { key = "N", mods = "Control|Shift", chars = "\u001b[80;6u" },

        { key = "Key0", mods = "Control", chars = "\u001b[48;5u" },
        { key = "Key1", mods = "Control", chars = "\u001b[49;5u" },
        { key = "Key2", mods = "Control", chars = "\u001b[50;5u" },
        { key = "Key3", mods = "Control", chars = "\u001b[51;5u" },
        { key = "Key4", mods = "Control", chars = "\u001b[52;5u" },
        { key = "Key5", mods = "Control", chars = "\u001b[53;5u" },
        { key = "Key6", mods = "Control", chars = "\u001b[54;5u" },
        { key = "Key7", mods = "Control", chars = "\u001b[55;5u" },
        { key = "Key8", mods = "Control", chars = "\u001b[56;5u" },
        { key = "Key9", mods = "Control", chars = "\u001b[57;5u" },
        { key = "Return", mods = "Control", chars = "\u001b[13;5u" },

        # https://github.com/alacritty/alacritty/issues/62#issuecomment-347552058
        # { key = "N", mods = "Alt", chars = "\u001bn" },
        # { key = "P", mods = "Alt", chars = "\u001bp" },
        # { key = "N", mods = "Alt", chars = "\x1bn" },
        # { key = "P", mods = "Alt", chars = "\x1bp" },
        # { key = "N", mods = "Alt", chars = "\u001b\u006e" },
        # { key = "P", mods = "Alt", chars = "\u001b\u0070" },

        { key = "N", mods = "Alt", chars = "\u001bn" },
        { key = "p", mods = "Alt", chars = "\u001bp" },
        { key = "N", mods = "Alt|Shift", chars = "\u001bN" },
        { key = "P", mods = "Alt|Shift", chars = "\u001bP" },
]
